# disable dns server
port=0

dhcp-range=10.30.9.90,10.30.9.98,255.255.240.0,8h
dhcp-option=3,10.30.0.1
dhcp-option=6,192.168.168.168

dhcp-match=set:bios,option:client-arch,0
dhcp-match=set:x64-uefi,option:client-arch,7
dhcp-match=set:x64-uefi,option:client-arch,9
dhcp-match=set:aarch64-uefi,option:client-arch,11
dhcp-match=set:ipxe,175
dhcp-match=set:x64-http,option:client-arch,16

dhcp-boot=tag:x64-uefi,ipxe.efi,,10.30.9.99
dhcp-boot=tag:bios,undionly.kpxe,,10.30.9.99
dhcp-boot=tag:aarch64-uefi,ipxe-arm64.efi,,10.30.9.99
dhcp-boot=tag:ipxe,boot.ipxe,,10.30.9.99
dhcp-boot=tag:x64-http,http://10.30.9.99:9080/ipxe.efi,,

dhcp-option-force=tag:x64-http,60,HTTPClient

# 下面是一些静态dhcp租约，可以按需设置
dhcp-ignore=tag:!known
#dhcp-host=ff:ff:ff:ff:ff:fa,192.168.88.101,bootstrap,set:known
#dhcp-host=ff:ff:ff:ff:ff:fa,set:known
